# Generated by Django 3.2.10 on 2022-02-15 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drfapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_enrolled',
        ),
        migrations.RemoveField(
            model_name='student',
            name='desciption',
        ),
    ]
